osx_image: xcode8
language: objective-c
script:
# iOS Static Lib
- xcodebuild -destination "platform=iOS Simulator,name=iPhone 7" -project ZipUtilities.xcodeproj -scheme ZipUtilities -sdk iphonesimulator10.0 build test
# iOS Framework (disabled since it requires code signing with latest Xcode and we don't provide a code signer with the open source project)
#- xcodebuild -destination "platform=iOS Simulator,name=iPhone 7" -project ZipUtilities.xcodeproj -scheme "ZipUtilities Framework" -sdk iphonesimulator10.0 build test
# Mac OS X (macOS) Framework
- xcodebuild -project ZipUtilities.xcodeproj -scheme "ZipUtilities OSX Framework" build test
