osx_image: xcode8
language: objective-c
script:
- xcodebuild -destination "platform=iOS Simulator,name=iPhone 7" -project ZipUtilities.xcodeproj -scheme ZipUtilities -sdk iphonesimulator10.0 build test
- xcodebuild -destination "platform=iOS Simulator,name=iPhone 7" -project ZipUtilities.xcodeproj -scheme "ZipUtilities Framework" -sdk iphonesimulator10.0 build test
- xcodebuild -project ZipUtilities.xcodeproj -scheme "ZipUtilities OSX Framework" build test
